version: "3"

vars:
  PLUGIN_NAME: Jellyfin.Plugin.GetAvatar
  PLUGIN_VERSION: 1.0.0.0
  TARGET_FRAMEWORK: net9.0
  PROJECT_PATH: "/Users/celian/Desktop/Github/jellyfin-plugin-GetAvatar"
  JELLYFIN_CONFIG_PATH: "/Users/celian/config/jellyfin"

  BUILD_DIR: "{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/bin/Debug/{{.TARGET_FRAMEWORK}}"
  DLL_PATH: "{{.BUILD_DIR}}/{{.PLUGIN_NAME}}.dll"
  XML_PATH: "{{.BUILD_DIR}}/{{.PLUGIN_NAME}}.xml"

  PLUGIN_DEST_PATH: "{{.JELLYFIN_CONFIG_PATH}}/plugins/{{.PLUGIN_NAME}}_{{.PLUGIN_VERSION}}"
  CONFIG_DIR: "{{.JELLYFIN_CONFIG_PATH}}/plugins/configurations"
  DOCKER_CONTAINER: jellyfin

tasks:
  build:
    desc: Build, Deploy and Restart
    cmds:
      - dotnet build '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}' -c Debug

      - sudo rm -rf "{{.JELLYFIN_CONFIG_PATH}}/plugins/{{.PLUGIN_NAME}}"*
      - sudo rm -rf "{{.JELLYFIN_CONFIG_PATH}}/plugins/GetAvatar"*
      
      - if [ ! -d "{{.PLUGIN_DEST_PATH}}" ]; then sudo mkdir -p "{{.PLUGIN_DEST_PATH}}"; fi
      - if [ ! -d "{{.CONFIG_DIR}}" ]; then sudo mkdir -p "{{.CONFIG_DIR}}"; fi

      - sudo cp -f "{{.DLL_PATH}}" "{{.PLUGIN_DEST_PATH}}/"
      - sudo cp -f "{{.XML_PATH}}" "{{.PLUGIN_DEST_PATH}}/"

      - sudo chown -R $(whoami):$(id -gn) "{{.PLUGIN_DEST_PATH}}"
      - sudo chmod 755 "{{.PLUGIN_DEST_PATH}}"
      - sudo chmod 644 "{{.PLUGIN_DEST_PATH}}/{{.PLUGIN_NAME}}.dll"
      - sudo chmod 644 "{{.PLUGIN_DEST_PATH}}/{{.PLUGIN_NAME}}.xml"

      - docker restart "{{.DOCKER_CONTAINER}}"

  clean:
    desc: Clean local bin, remove plugin and remove user avatars
    cmds:
      - rm -rf '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/bin' '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/obj'
      - if [ -d "{{.PLUGIN_DEST_PATH}}" ]; then sudo rm -rf "{{.PLUGIN_DEST_PATH}}"; fi
      
      # Remove plugin data (avatars stored by plugin)
      - if [ -d "{{.JELLYFIN_CONFIG_PATH}}/plugins/GetAvatar" ]; then sudo rm -rf "{{.JELLYFIN_CONFIG_PATH}}/plugins/GetAvatar"; fi
      
      - echo "Removing user avatars..."
      - sudo find "{{.JELLYFIN_CONFIG_PATH}}/data/metadata/users" -name "primary.jpg" -type f -delete
      
      - echo "Restarting Jellyfin..."
      - docker restart "{{.DOCKER_CONTAINER}}"
