version: "3"

vars:
  PLUGIN_NAME: Jellyfin.Plugin.GetAvatar
  PLUGIN_VERSION: 1.5.0.0
  TARGET_FRAMEWORK: net9.0
  PROJECT_PATH: "/Users/cedev/Desktop/github/jellyfin-plugin-GetAvatar"
  JELLYFIN_CONFIG_PATH: "/Users/cedev/config/jellyfin"

  BUILD_DIR: "{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/bin/Debug/{{.TARGET_FRAMEWORK}}"
  DLL_PATH: "{{.BUILD_DIR}}/{{.PLUGIN_NAME}}.dll"
  XML_PATH: "{{.BUILD_DIR}}/{{.PLUGIN_NAME}}.xml"

  PLUGIN_DEST_PATH: "{{.JELLYFIN_CONFIG_PATH}}/data/plugins/configurations/{{.PLUGIN_NAME}}"
  DOCKER_CONTAINER: jellyfin

tasks:
  build:
    desc: Build and deploy plugin to Jellyfin
    cmds:
      - echo "Building plugin..."
      - dotnet build '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}' -c Debug
      
      - echo "Cleaning old plugin versions..."
      - sudo rm -rf "{{.JELLYFIN_CONFIG_PATH}}/data/plugins/configurations/{{.PLUGIN_NAME}}"*
      
      - echo "Creating plugin directory..."
      - sudo mkdir -p "{{.PLUGIN_DEST_PATH}}"
      
      - echo "Copying plugin files..."
      - sudo cp -f "{{.DLL_PATH}}" "{{.PLUGIN_DEST_PATH}}/"
      - sudo cp -f "{{.XML_PATH}}" "{{.PLUGIN_DEST_PATH}}/"
      
      - echo "Setting permissions for LinuxServer Jellyfin user abc..."
      - docker exec {{.DOCKER_CONTAINER}} sh -c "chown -R 911:911 /config/data/plugins/configurations/{{.PLUGIN_NAME}} 2>/dev/null || true"
      - docker exec {{.DOCKER_CONTAINER}} sh -c "chmod 755 /config/data/plugins/configurations/{{.PLUGIN_NAME}} 2>/dev/null || true"
      - docker exec {{.DOCKER_CONTAINER}} sh -c "chmod 644 /config/data/plugins/configurations/{{.PLUGIN_NAME}}/*.dll 2>/dev/null || true"
      
      - echo "Restarting Jellyfin..."
      - docker restart {{.DOCKER_CONTAINER}}
      
      - echo "Done! Plugin deployed."

  clean:
    desc: Remove plugin and clean build files
    cmds:
      - rm -rf '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/bin' '{{.PROJECT_PATH}}/{{.PLUGIN_NAME}}/obj'
      - sudo rm -rf "{{.PLUGIN_DEST_PATH}}"
      - sudo rm -rf "{{.JELLYFIN_CONFIG_PATH}}/data/plugins/configurations/GetAvatar"
      - docker restart {{.DOCKER_CONTAINER}}

  check:
    desc: Check plugin status in Jellyfin
    cmds:
      - echo "Checking plugin directory..."
      - ls -la "{{.JELLYFIN_CONFIG_PATH}}/data/plugins/configurations/"
      - echo ""
      - echo "Checking permissions in container..."
      - docker exec {{.DOCKER_CONTAINER}} ls -la /config/data/plugins/configurations/ || echo "Container not running"
      - echo ""
      - echo "Checking Jellyfin logs for plugin loading..."
      - docker logs {{.DOCKER_CONTAINER}} 2>&1 | grep -i "GetAvatar" || echo "Plugin not found in logs"
